### Debug dart2js compiled code:
#targets:
#  $default:
#    builders:
#      build_web_compilers|entrypoint:
#        # These are globs for the entrypoints you want to compile.
#        generate_for:
#          - web/**.dart
#          - example/**.dart
#        options:
#          compiler: dart2js
#          # List any dart2js specific args here, or omit it.
#          dart2js_args:
#            - -O1
