name: chart_engine
description: Chart generator with interchangeable chart engines, like ChartJS and ApexCharts.
version: 2.1.0
homepage: https://github.com/Colossus-Services/chart_engine

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  swiss_knife: ^3.2.0
  dom_tools: ^2.3.0
  color_palette_generator: ^2.0.1
  amdjs: ^2.0.3
  intl: ^0.19.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  path: ^1.9.0
  dependency_validator: ^3.2.3
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  collection: ^1.18.0

#dependency_overrides:
#  swiss_knife:
#    path: ../swiss_knife
#  dom_tools:
#    path: ../dom_tools
#  color_palette_generator:
#    path: ../color_palette_generator
#  amdjs:
#    path: ../amdjs

