name: chart_engine
description: Chart generator with interchangeable chart engines, like ChartJS and ApexCharts.
version: 3.0.0-beta.1
homepage: https://github.com/Colossus-Services/chart_engine

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  swiss_knife: ^3.2.3
  dom_tools: ^3.0.0-beta.4
  color_palette_generator: ^2.0.1
  amdjs: ^3.0.0-beta.2
  intl: ^0.19.0
  web: ^1.1.0
  web_utils: ^1.0.6
  js_interop_utils: ^1.0.5

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  path: ^1.9.1
  dependency_validator: ^3.2.3
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.1
  collection: ^1.19.1

#dependency_overrides:
#  swiss_knife:
#    path: ../swiss_knife
#  dom_tools:
#    path: ../dom_tools
#  color_palette_generator:
#    path: ../color_palette_generator
#  amdjs:
#    path: ../amdjs

