name: chart_engine
description: Chart generator with interchangeable chart engines, like ChartJS and ApexCharts.
version: 1.1.11
homepage: https://github.com/Colossus-Services/chart_engine

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  swiss_knife: ^2.5.26
  dom_tools: ^1.3.20
  color_palette_generator: ^1.0.4
  amdjs: ^1.0.7
  intl: ^0.16.1

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
  path: ^1.7.0

#dependency_overrides:
#  swiss_knife:
#    path: ../swiss_knife
#  dom_tools:
#    path: ../dom_tools
#  color_palette_generator:
#    path: ../color_palette_generator
#  amdjs:
#    path: ../amdjs

