name: chart_engine
description: Chart generator with interchangeable chart engines, like ChartJS and ApexCharts.
version: 1.1.1
homepage: https://github.com/Colossus-Services/chart_engine

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  swiss_knife: ^2.5.4
    #path: ../swiss_knife
  dom_tools: ^1.3.2
    #path: ../dom_tools
  color_palette_generator: ^1.0.1
    #path: ../color_palette_generator
  amdjs: ^1.0.4
    #path: ../amdjs
  intl: ^0.16.1

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
  test: ^1.14.6

