name: chart_engine
description: Chart generator with interchangeable chart engines, like ChartJS and ApexCharts.
version: 1.1.6
homepage: https://github.com/Colossus-Services/chart_engine

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  swiss_knife: ^2.5.12
    #path: ../swiss_knife
  dom_tools: ^1.3.10
    #path: ../dom_tools
  color_palette_generator: ^1.0.2
    #path: ../color_palette_generator
  amdjs: ^1.0.6
    #path: ../amdjs
  intl: ^0.16.1

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.2
  test: ^1.15.3
  path: ^1.7.0
  pubspec: ^0.1.4
