name: chart_engine
description: Chart generator with interchangeable chart engines, like ChartJS and ApexCharts.
version: 3.0.0
homepage: https://github.com/Colossus-Services/chart_engine

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  swiss_knife: ^3.3.14
  dom_tools: ^3.1.0
  color_palette_generator: ^2.0.1
  amdjs: ^3.0.0
  intl: ^0.20.3
  web_utils: ^1.1.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.32.0
  path: ^1.9.1
  dependency_validator: ^5.1.0
  build_runner: ^2.16.2
  build_web_compilers: ^4.8.11
  collection: ^1.19.1

#dependency_overrides:
#  swiss_knife:
#    path: ../swiss_knife
#  dom_tools:
#    path: ../dom_tools
#  color_palette_generator:
#    path: ../color_palette_generator
#  amdjs:
#    path: ../amdjs

