name: chart_engine
description: Chart generator with interchangeable chart engines, like ChartJS and ApexCharts.
version: 2.0.4
homepage: https://github.com/Colossus-Services/chart_engine

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  swiss_knife: ^3.1.1
  dom_tools: ^2.1.1
  color_palette_generator: ^2.0.0
  amdjs: ^2.0.3
  intl: ^0.17.0
  collection: ^1.15.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.5
  path: ^1.8.0
  build_runner: ^2.0.4
  build_web_compilers: ^3.0.0

#dependency_overrides:
#  swiss_knife:
#    path: ../swiss_knife
#  dom_tools:
#    path: ../dom_tools
#  color_palette_generator:
#    path: ../color_palette_generator
#  amdjs:
#    path: ../amdjs

